name: Signing Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  package:
    env:
      GITHUB_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      MACOS_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
      MACOS_APP_SPECIFIC_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    name: Package for ${{ matrix.for }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            pack-command: ':macos'
            for: 'macos install kit'
            package-targets: 'darwin-x64'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Sign Executable (macOS)
        working-directory: ./packages/cli
        if: ${{matrix.os == 'macos-latest'}}
        run: |
          ls -n /Applications/ | grep Xcode*
          xcodebuild -version
          # security find-identity -v
          # echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          # security create-keychain -p ${{ secrets.MACOS_KEYCHAIN_PWD }} build.keychain
          # security default-keychain -s build.keychain
          # security unlock-keychain -p ${{ secrets.MACOS_KEYCHAIN_PWD }} build.keychain
          # security import certificate.p12 -k build.keychain -P ${{ secrets.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
