name: Signing Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  package:
    env:
      GITHUB_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      MACOS_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
      MACOS_APP_SPECIFIC_PWD: ${{ secrets.MACOS_KEYCHAIN_PWD }}
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    name: Package for ${{ matrix.for }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            pack-command: ':macos'
            for: 'macos install kit'
            package-targets: 'darwin-x64'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Sign Executable (macOS)
        working-directory: ./packages/cli/dist/macos
        if: ${{matrix.os == 'macos-latest'}}
        run: |
          ls /Applications/
          xcrun --version
